### ISSUE TITLE
Elgg 4x and and php 8x compatibility

### ISSUE THREAD

**Issue by daniyaree** [rjcalifornia/proposals#1]
A version working with Elgg 4x (and 5x thereafter) and php 8x will be highly appreciated.

**Comment by rjcalifornia** [comment]
> A version working with Elgg 4x (and 5x thereafter) and php 8x will be highly appreciated.

I'm working on a elgg 4.x version, it should be ready by friday.

**Comment by rjcalifornia** [comment]
A new version for elgg 4.x was release last week. You can find it here:

https://github.com/rjcalifornia/proposals/tree/elgg-4

https://elgg.org/plugins/3116001
